### ISSUE TITLE
radar 图绘制逻辑错误

### ISSUE THREAD

**Issue by itshizhan** [chmini-app/CHCharts-wechat#1]
1. 雷达图绘制的时候，MaxValue不能自定义。
2.MaxValue因为不能自定义。导致所有维度的值一样时，绘制错误。
3.最好应该提供一个非min的js。

**Comment by JiaoLiu** [comment]
感谢你的反馈。
1、本绘图组件不提供MaxValue是为了减少开发者使用组件时配置参数数量，以达到简单几行定义就可以绘制图表的目的。后续会考虑将这个参数加上，请关注后续迭代版本。
2、针对你提到的所有维度值一样绘制错误问题，我们测试并未发现错误，如果方便，麻烦提供你的测试数据。
3、目前工程未完全对外开放源码。
