### ISSUE TITLE
为啥有些图表没有动画效果？

### ISSUE THREAD

**Issue by skyopens** [chmini-app/CHCharts-wechat#4]
还有测量仪我把animation改为true的时候字体会变大，也没有动画过度。。。。

**Comment by JiaoLiu** [comment]
目前不是所有图都是配置了动画，有的图不太适合动画展示所以没有加，测量仪bug我们尽快定位。

**Comment by JiaoLiu** [comment]
测量仪的字体问题已在2.0.1中解决。
