### ISSUE TITLE
小程序显示

### ISSUE THREAD

**Issue by Psh-P** [chmini-app/CHCharts-wechat#5]
![image](https://user-images.githubusercontent.com/56905571/67356477-d9370900-f58c-11e9-8285-93e116d54235.png)
主要是这个x轴的显示问题很大，数据显示不完全，希望可以解决

**Comment by JiaoLiu** [comment]
好的，我们尽快处理。

**Comment by JiaoLiu** [comment]
问题已解决，请使用2.0.2版本～
